//! 关键依赖冻结表（v1.8 / F36-Phase2）
//!
//! ## 背景
//!
//! ComfyUI `requirements.txt` 只约束下界（`numpy>=1.23`），不约束上界。
//! 当 `pip install -r` 时，pip 会自动选择最新版，可能装到有问题的版本：
//!
//! **典型问题：numpy 2.4.4 wheel 缺 `exceptions.py`**
//! - 2025 年底 numpy 2.4.4 发布，wheel 包中 `numpy/exceptions.py` 文件丢失
//! - torch 2.4.x 依赖 `numpy.exceptions`，`import torch` 抛 ImportError
//! - 用户看到 PyTorch 装好了但显示"未安装"，因为 import 失败
//! - 旧版探针脚本 `except ImportError: installed=False` 把这个错误吞了
//!
//! ## 解决
//!
//! 安装 ComfyUI requirements 时**叠加**以下 `--constraint` 文件：
//! ```bash
//! uv pip install -r requirements.txt -c constraints.txt --python <venv>
//! ```
//!
//! constraints.txt 只**约束上界**（不强制装某版本），与 requirements.txt 的下界组合：
//! - requirements.txt 写 `numpy>=1.23` → 允许 1.23 ~ 2.x
//! - constraints.txt 写 `numpy<2.3` → pip 会选 2.2.x 最高可用版本（实测 2.2.6 正常）
//!
//! ## 设计原则
//!
//! - **只锁上界，不锁下界**：避免与 ComfyUI 升级冲突
//! - **条目精简**：只锁已知有问题的包（numpy / pydantic / typing-extensions 等）
//! - **可扩展**：新增条目只需追加到 `FROZEN_CONSTRAINTS`
//!
//! 详见 `PR/03-模块设计/02-PythonEnvManager.md §15 依赖冻结`

use std::fmt::Write;

/// 关键依赖冻结约束（key = 包名，value = 上界约束表达式）
///
/// 格式：PEP 508 风格，与 `pip install -c` 兼容
/// 示例：`<2.3` 表示 `pkg<2.3`（禁止装 >= 2.3 的版本）
///
/// ⚠ 严禁改下界（如 `>=2.0`）—— 会与 ComfyUI requirements.txt 的下界冲突，
/// 且 ComfyUI 升级时可能引入破坏性变化。
pub const FROZEN_CONSTRAINTS: &[(&str, &str)] = &[
    // numpy 2.4.x 已知问题：wheel 缺 exceptions.py（2025-12 报）
    // numpy 2.3.x 部分版本与 torch 2.4.x 存在 ABI 警告
    // 实测安全：numpy 2.0 ~ 2.2.6（含 2.2.6）
    ("numpy", "<2.3"),
    // typing-extensions 4.14+ 改变了 typing 别名机制，旧版 torch 可能不兼容
    ("typing-extensions", "<4.14"),
    // setuptools 80+ 不再支持 Python 3.8（若 venv 装 3.8 会 break）
    // 保留上界确保 venv 创建时不会装上
    ("setuptools", "<80"),
];

/// 生成 constraints.txt 内容（PEP 508 格式）
///
/// 输出示例：
/// ```text
/// # Auto-generated by freeze.rs - DO NOT EDIT
/// numpy<2.3
/// typing-extensions<4.14
/// setuptools<80
/// ```
pub fn render_constraints() -> String {
    let mut s = String::with_capacity(512);
    s.push_str("# Auto-generated by BoundLaunch freeze.rs - DO NOT EDIT\n");
    s.push_str("# Purpose: 关键依赖上界约束，防止 pip 拉来有问题的版本\n");
    s.push_str("# 详见 PR/03-模块设计/02-PythonEnvManager.md §15\n");
    s.push_str("\n");
    for (pkg, op_ver) in FROZEN_CONSTRAINTS {
        // 拼成 "pkg<2.3"（无空格，PEP 508 兼容）
        let _ = write!(s, "{}{}\n", pkg, op_ver);
    }
    s
}

/// 写入 constraints 文件到 venv 目录
///
/// 默认路径：`<venv>/.freeze-constraints.txt`
///
/// **为什么放在 venv 目录内**：
/// - 跟 venv 绑定，不同 venv 互不干扰
/// - 删 venv 时一起删，无残留
/// - 不污染用户项目目录
pub fn write_constraints_to_venv(venv_path: &std::path::Path) -> std::io::Result<std::path::PathBuf> {
    let path = venv_path.join(".freeze-constraints.txt");
    std::fs::write(&path, render_constraints())?;
    tracing::debug!(?path, "freeze constraints written");
    Ok(path)
}

/// 写 constraints 到临时目录（用于不在 venv 目录下的场景，如迁移）
///
/// 用于一次性迁移 numpy 2.4.4→2.2.6（避免写到 venv 目录被 venv 清理逻辑误删）
///
/// **实现说明**：用 `std::env::temp_dir()` + UUID 文件名创建临时文件，
/// 不引入 `tempfile` 依赖（tempfile 是 dev-dependency，生产代码用 std 即可）。
/// 文件名：`boundlaunch-freeze-{uuid}.txt`，避免冲突。
pub fn write_constraints_to_temp() -> std::io::Result<(std::path::PathBuf, std::fs::File)> {
    use std::io::Write;
    let unique = uuid::Uuid::new_v4();
    let path = std::env::temp_dir().join(format!("boundlaunch-freeze-{}.txt", unique));
    let mut file = std::fs::File::create(&path)?;
    file.write_all(render_constraints().as_bytes())?;
    file.flush()?;
    Ok((path, file))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_render_constraints_format() {
        let s = render_constraints();
        // 必须包含表头注释
        assert!(s.starts_with("# Auto-generated"));
        // 必须包含每个冻结项
        for (pkg, op) in FROZEN_CONSTRAINTS {
            let line = format!("{}{}", pkg, op);
            assert!(
                s.contains(&line),
                "render_constraints missing line: {}\nactual:\n{}",
                line,
                s
            );
        }
        // 必须以换行结尾
        assert!(s.ends_with('\n'));
    }

    #[test]
    fn test_frozen_constraints_format_valid() {
        // 每个 op_ver 必须是合法的 PEP 508 操作符 + 版本
        for (pkg, op_ver) in FROZEN_CONSTRAINTS {
            assert!(!pkg.is_empty(), "empty package name in FROZEN_CONSTRAINTS");
            let first = op_ver.chars().next().expect("empty op_ver");
            assert!(
                first == '<' || first == '>' || first == '!' || first == '=' || first == '~',
                "FROZEN_CONSTRAINTS[{}] invalid op: {}",
                pkg,
                op_ver
            );
        }
    }

    #[test]
    fn test_freeze_is_upper_bound_only() {
        // 强制约束：必须是上界（< 或 <=），避免与 ComfyUI requirements.txt 冲突
        for (pkg, op_ver) in FROZEN_CONSTRAINTS {
            assert!(
                op_ver.starts_with('<'),
                "FROZEN_CONSTRAINTS[{}] must be upper bound (<), got: {}",
                pkg,
                op_ver
            );
        }
    }
}
